### ISSUE TITLE
Add support for generating certificates for upstreams that are off-system

### ISSUE THREAD

**Issue by mossholderm** [fatk/docker-letsencrypt-nginx-proxy-companion-examples#18]
Add support for proxy destinations are "off-box" and not in docker containers. For example, It would be great to be able to have an Encrypted connection land on the nginx-proxy docker container, and then travel unencrypted to the destination server.

nginx-proxy support adding a configuration file to achieve this end, but nginx-letsencrypt has no method to handle generating/managing the certificates for this sort of situation.

Perhaps permit allowing some environment variables for passing in additional hostnames/emails for certificates that should be managed, regardless of container existence?

**Comment by fatk** [comment]
This repo is just lists examples on how to run existing docker images, so this is out of scope.

I think what you're trying to achieve might be doable using [an overlay network](https://docs.docker.com/engine/userguide/networking/get-started-overlay/) for nginx-proxy/proxy-tier network instead of bridge.
